name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2 using SSH

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/cloud-resource-scheduler

            git pull origin main

            source venv/bin/activate
            pip install plotly

            rm -f outputs/metrics/*.csv
            rm -f outputs/visualizations/*.png

            mkdir -p builds
            mkdir -p outputs/metrics
            mkdir -p outputs/visualizations

            gcc input_generator.c -o builds/gen

            g++ -std=c++17 main.cpp -o builds/run

            ./builds/gen

            ./builds/run

            python3 charts.py

            sudo systemctl restart cloudscheduler